### ISSUE TITLE
kodi-mpp-git should provide kodi-dev

### ISSUE THREAD

**Issue by kyak** [7Ji-PKGBUILDs/.meta#27]
I've installed `kodi-mpp-git` package and now trying to build `kodi-addon-pvr-iptvsimple-git` package from AUR.

I don't really want to build [kodi-binary-addons](https://github.com/hbiyik/agrrepo/blob/master/kodi/kodi-binary-addons-git/PKGBUILD) for several reasons: 1) it's huge and really just an overkill for my use case, 2) it requires `agr` which is yet another tool for me (I already have to think about AUR packages and manage them), 3) it doesn't work with `makepkg` (chokes on gitweb-dlagent).

However, `kodi-addon-pvr-iptvsimple-git` requires `kodi-dev`. It looks like development headers are already provided by `kodi-mpp-git` (otherwise, `kodi-binary-addons` would not have built).

I think that `kodi-mpp-git` should provide `kodi-dev`.

**Comment by 7Ji** [comment]
Whether to add that or not is something that should be decided by @hbiyik

But a few refs here:
 - `kodi` provides `kodi-dev`: https://gitlab.archlinux.org/archlinux/packaging/packages/kodi/-/blob/53526ff1d7cb7ed81870f35f3638807c17474d6c/PKGBUILD#L21
 - `kodi-git` splits to `kodi-git-dev`: https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=kodi-git&id=f6b2fe0e829668636303a5a6c7a50023b4852f04#n27 , which then provides `kodi-dev`: https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=kodi-git&id=f6b2fe0e829668636303a5a6c7a50023b4852f04#n281

**Comment by 7Ji** [comment]
A placeholder PKGBUILD as a workaround:
```
pkgname='kodi-dev-placeholder'
arch=('any')
pkgver=20.5
pkgrel=1
provides=("kodi-dev=${pkgver}")
```

**Comment by hbiyik** [comment]
This wont work with kodi-mpp because it is following git (Omega) branch
https://aur.archlinux.org/packages/kodi-addon-pvr-iptvsimple-git

This however will work with kodi-mpp since it is following Nexus Branch.
https://aur.archlinux.org/packages/kodi-addon-pvr-iptvsimple

They all depend on kodi-dev, without specifying a version.

Even if the addons specify a strict kodi version, kodi-mpp is git package so version will be very dynamic. I think a better way would be that they would depend on a virtual pkgname like kodi-nexus-dev

Since there is no such thing i will just enable kodi-dev and kodi-nexus-dev and now users can decide which aur package to choose from (nexus or omega or whatever version).

BTW when i switch from Nexus->Omega most likely users would need to swap addon packages, since im not so sure how to synchronize everything.

For inputstream-adaptive below should work:
https://aur.archlinux.org/packages/kodi-addon-inputstream-adaptive-any

For ffmpeg-direct below should work:
https://aur.archlinux.org/packages/kodi-addon-inputstream-ffmpegdirect

Updated in commit
https://github.com/7Ji-PKGBUILDs/kodi-mpp-git/commit/a2377f072f37d23adf95fcc18bf01f983fc32a56

**Comment by hbiyik** [comment]
Bonus:
You can also use 
https://aur.archlinux.org/packages/kodi-ext-git

instead of kodi-mpp which uses Omega branch, and external system-ffmpeg, then you need to switch to -git variants of addons.

Kodi-ext should work with ffmpeg-mpp, until it does not, as i previously said, running kodi-git is always an adventure, you never know when it will break.

**Comment by kyak** [comment]
> Updated in commit
> [7Ji-PKGBUILDs/kodi-mpp-git@a2377f0](https://github.com/7Ji-PKGBUILDs/kodi-mpp-git/commit/a2377f072f37d23adf95fcc18bf01f983fc32a56)

Thanks! Is something needed to be done for this to be picked up by the 7Ji's repo? `kodi-mpp-git` was last built on the 9th of March.

**Comment by hbiyik** [comment]
nothing but waiting, or you can compile aur packages ignoring the dependencies, without this change they should still build when deps are ignored
