### ISSUE TITLE
`panfork`: what happened? maintainability?

### ISSUE THREAD

**Issue by 7Ji** [7Ji-PKGBUILDs/.meta#34]
It seems all repos were purged from panfork gitlab org: https://gitlab.com/panfork after [Icecream95](https://gitlab.com/icecream95) (the one behind panfork) came back to activity recently.

This affects our `mesa-panfork-git` and `dri2to3-git` PKGBUILDs, but luckily @hbiyik has backed up the repos and switched the upstreams in https://github.com/7Ji-PKGBUILDs/mesa-panfork-git/commit/447e3bd973ff3a558a47a0126be8c4757f153a9b and https://github.com/7Ji-PKGBUILDs/dri2to3-git/commit/7530eda963aef6764841c4a37bd90b8ed5f2ebd6

Were these repos considered deprecated by icecream95 themself because of the improvements of collabora? Or was this a continuation of the "panfork" drama? 

I think we'll still need `mesa-panfork-git` for a long time before panthor lands in 6.10. Maintaining this by ourselves and patching it to follow mesa updates would not be an easy task. Should we drop these PKGBUILDs altogether when panthor reaches mainline?

**Comment by hbiyik** [comment]
i dont know the reason, but i think may be the fact that he does not have to just explains it.
May be this is the way of him telling that, he just made this work just to provide a solution until panthor is released. But he did not mention anything just not to deal with any drama... But this is me reading in between lines. I have no clue, and i dont know the drama at all.

Frankly speaking his repos were deprecated anyways since last year, so for me the situation dont change much.

> I think we'll still need `mesa-panfork-git` for a long time before panthor lands in 6.10

I had already done this, so you can run [panthor kernel driver in 6.1 rockchip bsp](https://github.com/hbiyik/linux-rockchip/tree/rk-6.1-rkr1-panthor-v6) allready.

I think there is even an [armbian patch](https://github.com/armbian/build/pull/6459) for it. There is also an [arch package](https://github.com/hbiyik/agrrepo/tree/master/kernel/rockchip/linux-aarch64-rockchip-bsp6.1-joshua-panthor-git) here.

> Should we drop these PKGBUILDs altogether when panthor reaches mainline?

I interpret both packages endemic pieces of software, both panthor on rockchip 6,1 or panfork mesa driver. They wont have any fix or future maintenance, in case needed i can take care of them.

But i really think panfork is a very interesting software from the idea point of view, and i would like to keep them both as a preference.

**Comment by 7Ji** [comment]
So let's keep mesa-panfork codebase and these PKGBUILDs.
