### ISSUE TITLE
Black screen with Kodi and 10-bit HEVC

### ISSUE THREAD

**Issue by erayrafet** [7Ji-PKGBUILDs/.meta#46]
DRM Prime is enabled, using the Khadas Edge2 with Joshua Kernel 6.1.75, Panthor and Mesa drivers from ALARM.
![image](https://github.com/user-attachments/assets/add0a081-366c-4c28-af62-1fc3b02dc02d)

**Comment by 7Ji** [comment]
Can confirm, tried 3.[HEVC 10-bit 59.94fps](https://drive.google.com/file/d/0BwxFVkl63-lEdVBuZkltckdZZ0k/view?usp=sharing&resourcekey=0-k91iv2m3Plumc5jdKCbxdQ) (Korean ATSC 3.0 satellite TV capture sample) from https://kodi.wiki/view/Samples and it also showed black screen on both bsp 6.1 + panthor + gbm/x11/wayland and bsp5.10 + panfork +gbm/x11/wayland (with blob or not)

@hbiyik Sorry for the ping, but was this a known problem or was it only introduced after some key events like ffmpeg 7 update?

**Comment by hbiyik** [comment]
Kodi can only render 10bit files under GBM. X11 or wayland can not render 10bit files. This is an issue with mesa.

Under GBM, vop2 kernel driver has several issues, i fixed them with rock5b but not 100% sure it can be applied to other devices due to random DTS configs all devices have their own.

However i will check it on rock5b if it still works there, if it works then it should be a problem related to khadas drm plane config.

**Comment by hbiyik** [comment]
@erayrafet could you provide kodi.log with debug logging enabled when kodi is ran with gbm mode?

**Comment by erayrafet** [comment]
> @erayrafet could you provide kodi.log with debug logging enabled when kodi is ran with gbm mode?

My keyboards and mouse won't do anything while running Kodi under GBM. 🤔

**Comment by hbiyik** [comment]
you can use yatse mobile application to control kodi, or you should allow your logged in user to acces input devices, i think it should be `input` group but now sure, you can google it.

in any case i think your issue is known since you dont use gbm.

On the other hand gbm mode also has issues now in Omega, i have created a PR for kodi upstream in 
https://github.com/xbmc/xbmc/pull/25588.

**Comment by hbiyik** [comment]
@7Ji i have changed the patch structure of kodi-mpp-git package so i had to overwrite your last commit.

I am strictly following upstream PRs now, if they are merged, i create and verify b2sum of the patches, because during the review process, upstream PRs might receive some cosmetic changes and verification might fail.

When skipped, it will use the last working cached version, which is functionally working.

**Comment by 7Ji** [comment]
Can you track them in pkgver or as git sources? In the current form with the same PKGBUILD commit + pkgver there could be different build targets. Updating in this case is broken for both users and the builder.

**Comment by hbiyik** [comment]
closing the issue then, @erayrafet when GBM is not used, there is no way to decode HDR content in kodi.
