### ISSUE TITLE
Introducing `linux-aarch64-rockchip-joshua-git`

### ISSUE THREAD

**Issue by kwankiu** [7Ji-PKGBUILDs/.meta#48]
@7Ji, @wyf9661, @hbiyik FYI.

Joshua has released a [new kernel](https://github.com/Joshua-Riek/linux-rockchip/tree/oracular) which is a mainline kernel with focus on rockchip/rk3588.
(FYI, he said he will be supporting `ubuntu oracular` for 9 months)

And I have created the PKGBUILD modified for this kernel and is available at https://github.com/7Ji-PKGBUILDs/linux-aarch64-rockchip-joshua-git

@7Ji, would you consider adding this to https://github.com/7ji/archrepo ?

**Comment by 7Ji** [comment]
There's no need to open an issue for every PKGBUILD you create. This org is mostly for PKGBUILD storage and I think as long as you created a repo that's actually a buildable PKGBUILD then you can push it, without notifying everybody.

And for repo addition. Currently the repo builder is down and under migration to a VM on a Huawei Kunpeng-920 server, so I would have plenty of CPU resources for building after migration. Can you verify it builds and boots successfully? If so I can add it to the build list.

**Comment by 7Ji** [comment]
For future PKGBUILDs, please init the repo with branch `master` instead of `main`. The builder defaults to `master` branch and only would checkout other branch when explicitly told to do so. I've renamed the branch for you.

**Comment by kwankiu** [comment]
sure

> And for repo addition. Currently the repo builder is down and under migration to a VM on a Huawei Kunpeng-920 server, so I would have plenty of CPU resources for building after migration. Can you verify it builds and boots successfully? If so I can add it to the build list.

Good to know that, i am currently experimenting with OCI I have previously tried to run arb inside a docker or lxc but it usually gives chroot mount errors.

i think it builds fine, i will test it out soon.

**Comment by kwankiu** [comment]
> For future PKGBUILDs, please init the repo with branch `master` instead of `main`. The builder defaults to `master` branch and only would checkout other branch when explicitly told to do so. I've renamed the branch for you.

Thanks, I didnt realise that until I actually build that package with arb as github now defaults to main instead of master

**Comment by 7Ji** [comment]
> Thanks, I didnt realise that until I actually build that package with arb as github now defaults to main instead of master

I would still define `master` to be arb's default branch, as that's what AUR uses, and I still want these PKGBUILDs to be able to be seamlessly synced to AUR, even if we can't currently due to x86_64-only rules.

> Good to know that, i am currently experimenting with OCI I have previously tried to run arb inside a docker or lxc but it usually gives chroot mount errors.

I don't recommend anybody to dig into `arb` 's `production` branch (currently default). It strictly needs root permission to set up mounts, which is a big security hole, and it had many design flaws. I started to rewrite it in `rewrite` branch a couple of months ago but the rewrite stops from time to time as my interest jumped from projects to projects and I have a full-time job that takes most of my time. 

Anyway, I've finished the migration and the PKGBUILD was added to the repo list, and a build was successful. Please wait for the online repo to be synced.
